### ISSUE TITLE
Remove Cro::HTTP dependency

### ISSUE THREAD

**Issue by patrickbkr** [croservices/cro-webapp#25]
I think there is a usecase of using the Cro templating engine outside of a server application. So it might be worthwhile to make the dependency on Cro::HTTP optional as to not pull in the entire Cro stack.

Background: I'm building an application that creates an HTML page from a set of templates and input data and then turns it into a PDF using a dedicated HTML-to-print document rendering engine (yes, such things exist). That PDF is then sent via an email that will probably also be layed out with HTML. So there are two use-cases in one application for an HTML templating system outside of the context of a HTTP server. (Admittedly, this application actually is a web service, so in my specific case I don't mind the extra dependency on Cro::HTTP, but the general idea remains valid).

**Comment by jnthn** [comment]
The `Cro::WebApp` distribution is already more than the template engine - see the recently added forms support - and will only grow to be that way. Further, the various things it provides don't stand alone; for example, the templates prelude includes the `form` function for form rendering. Support for translated strings is coming, and it will cross-cut forms and the template engine. Both templates and forms have integration with the HTTP router, and presumably there'll be some level of that for translation infrastructure too, since that property attaches to a request.

If anything happens in this space, it would be to extract the template engine to a `Cro::Template` module. However, it'd need some work to figure out how exactly we separate out the aspects of it that do depend on the HTTP router and other `Cro::WebApp` features.

**Comment by patrickbkr** [comment]
Let's close this issue. I think there is not much value in lengthening the issue list, without being actionable.
